
package com.company.productapp.ui;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.FormItem;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.IntegerField;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.component.textfield.TextField;


public class PopupViewProduct extends VerticalLayout
{

	/**
	 *
	 */
	public PopupViewProduct()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.formLayout        = new FormLayout();
		this.formItem          = new FormItem();
		this.labelImageUrl     = new Label();
		this.textFieldImage    = new TextField();
		this.formItem2         = new FormItem();
		this.labelName         = new Label();
		this.textFieldName     = new TextField();
		this.formItem3         = new FormItem();
		this.labelDesc         = new Label();
		this.textFieldDesc     = new TextField();
		this.formItem4         = new FormItem();
		this.labelCategory     = new Label();
		this.textFieldCategory = new TextField();
		this.formItem5         = new FormItem();
		this.labelPrice        = new Label();
		this.numberFieldPrice  = new NumberField();
		this.formItem6         = new FormItem();
		this.labelWeight       = new Label();
		this.numberFieldWeight = new NumberField();
		this.formItem7         = new FormItem();
		this.labelStock        = new Label();
		this.integerFieldStock = new IntegerField();
		this.horizontalLayout  = new HorizontalLayout();
		this.buttonSave        = new Button();
		this.buttonCancel      = new Button();

		this.formLayout.setResponsiveSteps(
			new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("500px", 2, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("1000px", 3, FormLayout.ResponsiveStep.LabelsPosition.ASIDE));
		this.labelImageUrl.setText("ImageURL");
		this.labelName.setText("Name");
		this.labelDesc.setText("Description");
		this.labelCategory.setText("Category");
		this.labelPrice.setText("Unit Price");
		this.labelWeight.setText("Unit Weight");
		this.labelStock.setText("Units in stock");
		this.buttonSave.setText("Save");
		this.buttonCancel.setText("Cancel");

		this.labelImageUrl.setSizeUndefined();
		this.labelImageUrl.getElement().setAttribute("slot", "label");
		this.textFieldImage.setSizeUndefined();
		this.formItem.add(this.labelImageUrl, this.textFieldImage);
		this.labelName.setSizeUndefined();
		this.labelName.getElement().setAttribute("slot", "label");
		this.textFieldName.setSizeUndefined();
		this.formItem2.add(this.labelName, this.textFieldName);
		this.labelDesc.setSizeUndefined();
		this.labelDesc.getElement().setAttribute("slot", "label");
		this.textFieldDesc.setSizeUndefined();
		this.formItem3.add(this.labelDesc, this.textFieldDesc);
		this.labelCategory.setSizeUndefined();
		this.labelCategory.getElement().setAttribute("slot", "label");
		this.textFieldCategory.setSizeUndefined();
		this.formItem4.add(this.labelCategory, this.textFieldCategory);
		this.labelPrice.setSizeUndefined();
		this.labelPrice.getElement().setAttribute("slot", "label");
		this.numberFieldPrice.setSizeUndefined();
		this.formItem5.add(this.labelPrice, this.numberFieldPrice);
		this.labelWeight.setSizeUndefined();
		this.labelWeight.getElement().setAttribute("slot", "label");
		this.numberFieldWeight.setSizeUndefined();
		this.formItem6.add(this.labelWeight, this.numberFieldWeight);
		this.labelStock.setSizeUndefined();
		this.labelStock.getElement().setAttribute("slot", "label");
		this.integerFieldStock.setSizeUndefined();
		this.formItem7.add(this.labelStock, this.integerFieldStock);
		this.formLayout.add(this.formItem, this.formItem2, this.formItem3, this.formItem4, this.formItem5,
			this.formItem6,
			this.formItem7);
		this.buttonSave.setSizeUndefined();
		this.buttonCancel.setSizeUndefined();
		this.horizontalLayout.add(this.buttonSave, this.buttonCancel);
		this.formLayout.setSizeUndefined();
		this.horizontalLayout.setSizeUndefined();
		this.add(this.formLayout, this.horizontalLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private FormLayout       formLayout;
	private Button           buttonSave, buttonCancel;
	private NumberField      numberFieldPrice, numberFieldWeight;
	private IntegerField     integerFieldStock;
	private HorizontalLayout horizontalLayout;
	private Label            labelImageUrl, labelName, labelDesc, labelCategory, labelPrice, labelWeight, labelStock;
	private TextField        textFieldImage, textFieldName, textFieldDesc, textFieldCategory;
	private FormItem         formItem, formItem2, formItem3, formItem4, formItem5, formItem6, formItem7;
	// </generated-code>
	
}
